---
title: "Data analysis project"
author: "Jess Qualley and Rebecca Hansen"
date: "March 27, 2020"
output: word_document
---
##Clear code (**delete before submitting***)
```{r}
rm(list = ls(all = TRUE))
```

#Preparation
##Loading and citing packages
```{r, echo = TRUE}
#Load faraway package
library(faraway)

#Load plyr package
library(plyr)

#Load tidyverse package
library(tidyverse)

#Cite packages
citation("faraway")
citation("plyr")
citation("tidyverse")
```

##Read in and organize data
```{r, echo = TRUE}
#Read from csv file
herring <- read.csv("HerringOtolithDatabase 15 Jan 2020_JQ.csv", header=TRUE, fileEncoding="UTF-8-BOM")

#Create a data frame
herring_data <- data.frame(sal.id = herring$FishCode,
                           her.id = herring$PreyID,
                           oto.width = herring$AverageWidth,
                           digestion = herring$Digestion,
                           sal.sp = herring$SalmonSpecies,
                           sal.sex = herring$SalmonSex,
                           sal.length = as.numeric(herring$SalmonLength),
                           sal.weight = herring$SalmonWeight,
                           coll.year = herring$CollectionYear,
                           coll.doy =   herring$CollectionDayofYear,
                           lat = herring$Latitude,
                           long = herring$Longitude)
```

##Checking our work (***delete before submitting***)
```{r, echo = TRUE}
#plot lat/long as continuous variable
plot(herring_data$long, herring_data$lat, xlim = c(-122, -128), ylim = c(48, 50.5))
```

##Example 1 (***delete before submitting)
```{r, echo = TRUE}
#add column for number of rows
n <- nrow(herring_data)
herring_data$row <- 1:n

par(mfrow = c(3, 2))

#otolith width
with(herring_data, plot(oto.width, row, las = 1, type = "n", xlab = "Otolith width [mm]", ylab = "Row Number"))
abline (h = seq(1, n, by = 5), col = "lightgrey")
with(herring_data, points(oto.width, row, las = 1, type = "p", pch = 19, cex = 0.5))

#actual salmon length - all salmon that ate herring - note that some numbers are ranges and have weird symbols...
#where lengths were not recorded, they were calculated using length-weight relationship
with(herring_data, plot(sal.length, row, las = 1, type = "n", xlab = "Actual Salmon Length [mm]", ylab = "Row Number"))
abline (h = seq(1, n, by = 5), col = "lightgrey")
with(herring_data, points(sal.length, row, las = 1, type = "p", pch = 19, cex = 0.5))

#actual salmon weight - raw salmon weights no back calculations
with(herring_data, plot(sal.weight, row, las = 1, type = "n", xlab = "Actual Salmon Weight [lbs]", ylab = "Row Number"))
abline (h = seq(1, n, by = 5), col = "lightgrey")
with(herring_data, points(sal.weight, row, las = 1, type = "p", pch = 19, cex = 0.5))

#day of year
with(herring_data, plot(coll.doy, row, las = 1, type = "n", xlab = "Day of Year in 2018", ylab = "Row Number"))
abline (h = seq(1, n, by = 5), col = "lightgrey")
with(herring_data, points(coll.doy, row, las = 1, type = "p", pch = 19, cex = 0.5))

#lat
with(herring_data, plot(lat, row, las = 1, type = "n", xlab = "Latitude", ylab = "Row Number"))
abline (h = seq(1, n, by = 5), col = "lightgrey")
with(herring_data, points(lat, row, las = 1, type = "p", pch = 19, cex = 0.5))

#long
with(herring_data, plot(long, row, las = 1, type = "n", xlab = "Longitude", ylab = "Row Number"))
abline (h = seq(1, n, by = 5), col = "lightgrey")
with(herring_data, points(long, row, las = 1, type = "p", pch = 19, cex = 0.5))
```


##Example 2 (***delete before submitting)
```{r, echo = TRUE}
#create data frame for pairwise scatter with only continuous explanatory variables - salmon lenght, weight and collection day of year
herring_collinearity <- data.frame("sal.length" = herring_data$sal.length, "sal.weight" = herring_data$sal.weight, "coll.doy" = herring_data$coll.doy, "lat" = herring_data$lat, "long" = herring_data$long)

#create pairwise scatterplot with salmon length, weight and day of year
plot(herring_collinearity[1:5], cex = 0.5, pch = 19, col = rgb(0, 0, 0, 0.5), 
                   labels = c("Chinook\nLength [mm]", "Chinook\nWeight [lbs]", "Collection\nDay in 2018", "Latitude", "Longitude"))

#pairwise correlation coefficients for multiple variables
print(cor(na.omit(herring_data[ ,c("sal.length", "sal.weight", "coll.doy", "lat", "long")])), digits = 2)

#variance inflation factors
print(vif(na.omit(herring_data[ ,c("sal.length", "sal.weight", "coll.doy", "lat", "long")])))
```

##Example 3 (***delete before submitting)
```{r, echo = TRUE}
#Make a table of salmon ID versus digestion state
with(herring_data, table(sal, digestion))

#Make a table of salmon ID versus sex
with(herring_data, table(sal.id, sal.sex))
```

##Example 4 (***delete before submitting)
```{r, echo = TRUE}
#Make a table of 0 values and NAs
table(herring_data_2018 > 0, useNA = "always")
```

##Cleaning data
```{r, echo = TRUE}
#filter only chinook and data from 2018 with na removed
herring_data_2018 <- herring_data %>% filter(herring_data$sal.sp == "ch" & herring_data$coll.year == "2018") %>% na.omit()
```